language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest
deploy:
  provider: pypi
  user: joranhonig
  password:
    secure: VQG9IxgTBrWjjQWnfpe1P3v9Sz9Yd+K/kY8snFSLeGw2GStcbvBb8CGShqRG8bYemfw8gEcO2oHR/yGcFFk6PE6xWSxb1Knmn/pLdwM1IO3AfL2WBvznuK6vn0jWwZYlayRyWdTmDTXZ428Q1d/t1ilNMvNKmf5EZ2jUHGi+Pca1t/Q0AH/DIQbBFGb8PnmGNHkmzcAisTHoHy6VVGk/j/F93unOH7zA5nLtKcUxA83ncRd9cwSNyi/upHBgnzKBnvxrUyqikwZ3QD1ULl/s5tGrUDQSNJjHNvH7RVSLYYk8TVBaNNRWEnaXK3HCMC5eh+Bnf5F7H989fLxGfN12p/wyR2XyroLr4MTET/qR7N6CkXedwbXf6n1UQargspg8YyzsLhW8CAh07uVacZtW1lhJMv1LXYUjgtJ9necvWw308r0eLdZZb8aSxXy6Bjg75mYR0ZEpIwrsmBuTbMzJwJVeDzOKYLSYgQnT2CKhdK7S5N7eZdwgWwb6S1ZVQfN8Keci4R29R6ZEUmWXs5bHGxpzvG8x4IoBnW8WD9cqmCYRsZlg6n5g/+jA2nOFBIf7wCBlw1wSCmL2xmIZuOGuJnXgSdEjc4SVQcyBaH02niGtbYmzYRj9izAgbpzl9F5dIiEaovnQ8/jjzTMyuAUbFerrD7AFAC/wrOY/lNccnhs=
  on:
    tags: true
    python: 3.6
  twine_version: latest
  distributions: sdist bdist_wheel
  skip_cleanup: true
