language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
script:
- pytest

deploy:
  provider: pypi
  user: joranhonig
  password:
    secure: W+kZZWGaDHEEO8lhvdqKuLP3o1XurIqwEJIGKOGrBxKl+mos3mD4PDdg04DEAtDC7vueynEZOnQikJN0nl4LUCcpl/soSSuyjH4iUfowCduoIFm9bd/ocpd1N8zryO4j/4nsnQn5gWMWuAV3+eDj6SNifLKdOn0TJn8fCvcTwWt1FmpfmVIGPnFQ1loZBI0Yw0i3GwwBp0n1BWYtVXyIoJXgtNhBvugrccKVmlMFtZr7hXicBf/BNO7Tsl5V3L9UFqKnLBDnwb1xvkrGX3KerKLP2fQMFxxpuL7c7YAx5IhD40C3WtFZkdwoqZBLbyRUNtQjo5J6/yDWLvK1waNZEWaFC/aSEKYofK+TQSGRmj9QLOLvF0eaV/cx0aqffS3a22EMYYYH5o1YtOAi15A3pnA+wkZKqopsurhvr5rPOwMt3Z/YQgAqJcPwJosS7Nnn8J45KerfVdSn4D+QpDId2z+mH20OII5sI6uF3XyzOOYJ6+u0r9r+KxM1VfWjxdtdlg2NqTeS2NeyimxMQ4+HYxsZ9+FRfgPyDqL6hTcLug4wNCV8E+wGzPjusUe2f9iwRodfD+4ZlrSWIxNqCUgGrWwbJByOWeEe6P3OQnkSGUMKBw1k3gesZkoJJ7iOHUrBX08QqWbsi3K7J6k8OBpei10Q9d2cLf596ZVZfS+GbNA=
  on:
    tags: true
    python: 3.6
  twine_version: latest
  distributions: "sdist bdist_wheel"
  skip_cleanup: true